# Generated by Django 6.0.3 on 2026-04-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('has_fines', models.BooleanField(default=False)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
